language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
install:
  - npm install
script:
  - npm run cp
  - npm run build
  - npm run publish
after_success:
  - npm run travis-deploy-once
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
# Send coverage data to Coveralls
