language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - npm install
script:
  - npm run cp
  - npm run build
after_success:
  - npm run travis-deploy-once
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
# Send coverage data to Coveralls
