language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
install:
  - npm install
script:
  - npm run cp
  - npm run build
after_success:
  - npm run travis-deploy-once
  - npm run semantic-release-pre
  - npm run-script publish
  - npm run semantic-release-post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
# Send coverage data to Coveralls
